<%@ Page Title="" Language="C#" MasterPageFile="~/ChatScreen.Master" AutoEventWireup="true" CodeBehind="Chat.aspx.cs" Inherits="chat1.Chat" %>
<asp:Content ID="HeadContent" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            height: 20px;
        }
        li{
            font-size:30px;
            list-style-type:none;
            
            
        }
        .msg{
            flex-direction:row-reverse;
            background-color:aquamarine;
            border-bottom-left-radius:10px;
            border-top-left-radius:10px;
            border-top-right-radius:10px;
            border-bottom-right-radius:0px;
            width:min-content;
        }
        msglist{
            
        }
     
          .auto-style2 {
            overflow: scroll;
            height: 500px;
            margin-right: 0px;
        }
        .auto-style3 {
            height: 20px;
            width: 328px;
        }
          </style>
</asp:Content>
<asp:Content ID="ChatContent2" ContentPlaceHolderID="ChatDetails" runat="server">



    <table style="width:100%;">
        <tr>
            <td class="auto-style3" rowspan="3">
                <div class="auto-style2">
                <ul>
                    <li >USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>
                    <li>USER</li>

                </ul>
                    </div>
            </td>
            
            <td class="auto-style1">name</td>
        </tr>
        <tr>
            <td>
                 <ul  id="discussion">
                 </ul>
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>
                 <input type="text" style="width:90%" id="message" />
                 <input type="button" style="width:10%" id="sendmessage" value="Send" />
                 <input type="hidden" id="displayname" />
            </td>
            <td>&nbsp;</td>
        </tr>
    </table>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-3.4.1.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.-->
    <script type="text/javascript">
        $(function () {
            // Declare a proxy to reference the hub.
            var chat = $.connection.chatHub;
            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (name, message) {
                // Html encode display name and message.
                var encodedName = $('<div />').text(name).html();
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page.
                $('#discussion').append('<li class="msglist"><div class="msg"><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</div></li>');
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub.
                    chat.server.send($('#displayname').val(), $('#message').val());
                    // Clear text box and reset focus for next comment.
                    $('#message').val('').focus();
                });
            });
        });
    </script>


</asp:Content>
